# ONBOARDING.ps1
Write-Host "=== VEIRONAUTO ONBOARDING ==="
Write-Host "1. Marchează taskurile în memory-bank/tasks.md și memory-bank/todo.md ([x])"
Write-Host "2. Rulează update-progress.ps1 pentru progres și log zilnic"
Write-Host "3. Folosește update-tasks.ps1 pentru batch complete și BLOCKED automat"
Write-Host "4. Folosește filter-tasks.ps1 pentru filtrare rapidă (BLOCKED/independent)"
Write-Host "5. Rulează check-files.ps1 pentru a verifica dacă fișierele din taskuri există fizic"
Write-Host "6. Citește README.md și QUICK_START.md pentru detalii și exemple"
Write-Host "7. Toate scripturile funcționează strict local, fără backend"
Write-Host "---"
Write-Host "Comenzi utile:"
Write-Host ".\update-progress.ps1"
Write-Host ".\update-tasks.ps1 -Batch 'Create booking.js,Create home.css'"
Write-Host ".\update-tasks.ps1" 
Write-Host ".\filter-tasks.ps1 -Filter 'BLOCKED'"
Write-Host ".\filter-tasks.ps1 -Filter 'independent'"
Write-Host ".\check-files.ps1" 